# Generated by Django 4.2.13 on 2026-05-10 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('webhook', 'Webhook Event'), ('ai_request', 'AI Request'), ('ai_error', 'AI Error'), ('api_error', 'API Error'), ('message_sent', 'Message Sent'), ('message_received', 'Message Received'), ('system', 'System')], db_index=True, max_length=30)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_traceback', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='clients.client')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['log_type', 'level', 'created_at'], name='logs_log_typ_5f60c5_idx')],
            },
        ),
    ]
