# Generated by Django 4.2.13 on 2026-05-10 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True)),
                ('green_api_message_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('ai_tokens_used', models.PositiveIntegerField(default=0)),
                ('ai_latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chat', 'created_at'], name='messages_chat_id_ec31ea_idx'), models.Index(fields=['direction', 'status'], name='messages_directi_a56436_idx')],
            },
        ),
    ]
