# Generated by Django 4.2.13 on 2026-05-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('chat_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('context_summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
    ]
