# Generated by Django 4.2.13 on 2026-05-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scenario', models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('general', 'General')], default='general', max_length=20)),
                ('system_prompt', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_ab_test', models.BooleanField(default=False)),
                ('ab_weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'db_table': 'prompts',
            },
        ),
    ]
